name: Blob storage website CI

on:
    push:
        branches: [master]
        paths:
          - 'Webpage/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name "rccstorage1" --auth-mode key -d '$web' -s Webpage/ --overwrite
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "rcc-cdn-profile" --name "mk-rcc-cdn-endpoint" --resource-group "CloudResumeChallenge"
  
  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
